baseURL: http://www.example.com
title: jomresearch
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
enableEmoji: yes
markup:
  highlight:
    noClasses: no
params:
  author: Jom Research
  avatarURL: images/avatar2.jpg
  colorScheme: auto
  commit: https://github.com/luizdepra/hugo-coder/tree/
  customCSS: []
  customJS: []
  customRemoteJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: Jom Research website
  hideColorSchemeToggle: no
  info:
    - We provide webinars related to research and statistical analysis
    - Do follow us on [Facebook](https://www.facebook.com/profile.php?id=100095502845075)
  maxSeeAlsoItems: 5
  rtl: no
  since: 2023
  social:
    - icon: fa fa-4x fa fa-facebook-square
      name: Facebook
      url: https://www.facebook.com/profile.php?id=100095502845075
      weight: 1
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
        - name: Webinars
          url: webinars/
          weight: 1
        - name: Consultation
          url: consultation/
          weight: 2
        - name: Trainers
          url: trainers/
          weight: 3
        - name: About
          url: about/
          weight: 4
        - name: Contact us
          url: contact/
          weight: 5

